Add internal tests for an lots flow
openprocurement/openprocurement.buildout pull request #94
Opened 2018-06-04 08:08 UTC by MichaelYusko

2018-06-06 12:01 UTC, oleksiyVeretiuk requested changes

2018-06-06 12:01 UTC, oleksiyVeretiuk commented on internal_tests/test_privatization.py
> +def patch_data(client, resource_id, data,
Чи справді ця функція є потрібною, адже в цьому випадку ти лише робиш проксі на іншу функцію. Я б зробив її більш специфічною тобто назвав її patch_auction(адже  ти тут патчиш нею тільки аукціони) і ще б вписав в неї тести на коректність цього патчу

2018-06-11 10:10 UTC, leits requested changes
З цього всього має бути лише 
`internal_tests\test_privatization.py`

2018-06-22 08:02 UTC, Leits commented on internal_tests/test_privatization.py
> +        self.assets_client.patch_resource_item(
Потрібні ще assert на перевірку, чи вдалося змінився статус.
І зробити дедублікацію цих патчів у окремий клас метод, якому передається новий статус

2018-06-27 12:32 UTC, Leits commented on internal_tests/test_privatization.py
> +        self.assertEqual(asset_data.data.status, 'pending')
Цей assert теж потрібно занести під `change_status`

2018-06-27 12:33 UTC, Leits commented on internal_tests/test_privatization.py
> +        self.assertEqual(asset_data.data.status, 'pending')
Можна зробити `change_status` методом класу переіменувавши на `change asset_status` i `self.assets_client` викликати всередині

2018-06-29 09:52 UTC, leits approved these changes

2019-05-07 06:59 UTC, closed without merging